theme: jekyll-theme-minimal
title: 刘建的个人主页
name: dreamerlark.github.io
email: liujian750806@gmail.com
description: 开始回忆

author:
  name: 刘建
  bio: 笨鸟多飞
  location: 中国 北京
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: "https://github.com/DreamerLark"
