minimal_mistakes_skin: default
theme: jekyll-theme-minimal
title: 刘建的个人主页
name: dreamerlark.github.io
email: liujian750806@gmail.com
description: 开始回忆
url: "https://dreamerlark.github.io"
remote_theme: mmistakes/minimal-mistakes@4.24.0

author:
  name: 刘建
  bio: 笨鸟多飞。
  location: 中国 北京
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: "https://github.com/DreamerLark"
